// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOuYcky-0_nPVEBRxScmAqnJJ-mMbW8BY',
    appId: '1:550440796041:web:cf89ed7572555fa26dab58',
    messagingSenderId: '550440796041',
    projectId: 'blog-app-with-firebase-98810',
    authDomain: 'blog-app-with-firebase-98810.firebaseapp.com',
    storageBucket: 'blog-app-with-firebase-98810.appspot.com',
    measurementId: 'G-BQYVC7N09C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Wq5YnYVfMAO2Y4y2F2nZC9HZyZ74eDI',
    appId: '1:550440796041:android:63cc22c44a4c2d206dab58',
    messagingSenderId: '550440796041',
    projectId: 'blog-app-with-firebase-98810',
    storageBucket: 'blog-app-with-firebase-98810.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIOYXNtOofOPPvLfadkXQL1Q46MDdW8eo',
    appId: '1:550440796041:ios:dbf2ee408e0211516dab58',
    messagingSenderId: '550440796041',
    projectId: 'blog-app-with-firebase-98810',
    storageBucket: 'blog-app-with-firebase-98810.appspot.com',
    iosBundleId: 'com.example.blogAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIOYXNtOofOPPvLfadkXQL1Q46MDdW8eo',
    appId: '1:550440796041:ios:db81c415ae49f95b6dab58',
    messagingSenderId: '550440796041',
    projectId: 'blog-app-with-firebase-98810',
    storageBucket: 'blog-app-with-firebase-98810.appspot.com',
    iosBundleId: 'com.example.blogAppWithFirebase.RunnerTests',
  );
}
